# Configuración del modelo YOLOv5 / YOLOv8
model:
  path: './runs/detect/train8/weights/best.pt'
  conf_thres: 0.4
  iou_thres: 0.5
  data: './data.yaml'

output:
  video_path: './output/output_video.avi'
  log_path: './output/log.txt'
  report_path: './output/detections_report.xlsx'

# Configuración del sistema
system:
  video_path: D:/YOLO/contruction_Monitoring/dataset/sample_video.mp4
  output_path: ./output
  log_path: ./logs

