# config.yaml

# Configuración del modelo YOLOv11
model:
  model:
  path: './weights/yolo11.pt'
  data: './data.yaml'
  conf_thres: 0.5
  iou_thres: 0.4

# Configuración del tracker
tracker:
  max_disappeared: 50
  max_distance: 100

# Configuración del sistema
system:
  video_path: './dataset/images/sample_video.mp4'
  output_path: './output/report.csv'
  log_path: './output/log.txt'
